# syntax=docker/dockerfile:1



ARG NODE_VERSION=21-bullseye

ARG PROJECT_PATH="./server/"

FROM node:${NODE_VERSION}

ARG PROJECT_PATH

WORKDIR /usr/src/app/server

COPY ${PROJECT_PATH} .

RUN npm install

COPY .env ../

ENV NODE_ENV production

RUN npm run build

EXPOSE 3001

CMD ["npm", "start"]