# syntax=docker/dockerfile:1

ARG NODE_VERSION=18.18.1

FROM node:${NODE_VERSION}-alpine

ARG PROJECT_PATH="./server/"

ENV NODE_ENV production


WORKDIR /usr/src/app/server

RUN --mount=type=bind,source=${PROJECT_PATH}package.json,target=package.json \
    --mount=type=bind,source=${PROJECT_PATH}package-lock.json,target=package-lock.json \
    --mount=type=cache,target=/root/.npm \
    npm ci --omit=dev

USER node

COPY ${PROJECT_PATH} .
COPY .env ../

EXPOSE 3001

CMD node server.js
